### ISSUE TITLE
Oops, Twitch's servers don't seem to be responding. Refresh?

### ISSUE THREAD

**Issue by Yocairo** [twireapp/Twire#309] opened 2022-02-14 20:15 UTC
Getting this error when loading "My streams", lately more often. It persists for quite a while.

**Comment by el-o-l** [comment] 2022-02-14 20:52
To follow up on this, whilst using the app it will eventually close the stream/or VOD and the above issue will persist. No followed streams, VODs of followed streamers, top streams or results in the search bar function, and for me this has occurred about every two days for several hours at a time.

**Comment by sonicrules1234** [comment] 2022-02-14 21:49
I've got this too.

**Comment by SirAmonThe1** [comment] 2022-02-14 22:17
Twitch seems to have changed something in the API. All third party software broke because of this

**Comment by zawnk** [comment] 2022-02-14 22:25
Twitch is switching to a new version of their API (and deprecates a lot of features along the way).
There are shutdown windows now, today there's a 4 hour one.

See [this blog post](https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/). At the end of February it's going to permanently deactivated.

**Comment by Nickwasused** [comment] 2022-02-16 07:42
Duplicate of #236 but I am leaving this open because most people don't look at the other Issue.

Here is the list of when the Servers are offline:
- February 7, 2022 – 1-hour shutdown starting at 11:00am PDT
- February 9, 2022 – 2-hour shutdown starting at 11:00am PDT
- February 14, 2022 – 4-hour shutdown starting at 11:00am PDT
- February 16, 2022 – 6-hour shutdown starting at 11:00am PDT
- February 21, 2022 – 24-hour shutdown starting at 11:00am PDT
- February 28, 2022 – v5 permanent shutdown

**Comment by Nickwasused** [comment] 2022-02-16 17:03
Fixed on next Release,

**Closed as completed** 2022-02-16 17:02 UTC
Labels: bug, duplicate
