### ISSUE TITLE
Unable to see my typed messages on chat

### ISSUE THREAD

**Issue by bikunoob** [twireapp/Twire#264] opened 2021-11-15 14:27 UTC
My messages are being relayed but I am not able to see them in the live chat box. I checked on a stream which had a live chat replay so my messages are visible to others but not me!! There is a blank region depending on the size of my messages in the chat box.

**Comment by JohnVeness** [comment] 2021-12-02 09:22
Dupe of #128?

**Closed** 2021-12-09 14:03 UTC
Labels: bug, duplicate
