### ISSUE TITLE
After doing initial setup and successfully reaching main screen, Back Button takes you back to initial setup screen

### ISSUE THREAD

**Issue by Dwedit** [twireapp/Twire#378] opened 2022-08-15 18:11 UTC
**Describe the bug**
Here is a minor bug that only happens the first time you use the program, and do the initial setup.

After you complete the initial setup process, pressing the Back button takes you to the initial setup pages again.

Meanwhile, if you run the program after having completed setup, you do not get this behavior.

**Smartphone (please complete the following information):**
 - Device: Moto G7 Power
 - Android Version: 10
 - Twire Version: 2.10.4

**Comment by samfundev** [comment] 2023-03-25 16:22
Duplicate of #10

**Closed by samfundev** 2023-03-25 16:22 UTC
Labels: bug, duplicate
