### ISSUE TITLE
Twire crash as soon you click on one of the stream after an update

### ISSUE THREAD

**Issue by PLAYERUNKNOWNHatsune01** [twireapp/Twire#282] opened 2021-12-12 01:29 UTC
Twire crashing so much after I update it. I try to clear data, uninstall and reinstalled again but the crashing is still there

https://user-images.githubusercontent.com/75108124/145697049-c92a9c2f-4efc-4ee4-8a64-03fab9591d72.mp4

**Comment by Hariiiiiiii** [comment] 2021-12-12 20:08
`12-12 10:28:41.300 18149 18149 E AndroidRuntime: FATAL EXCEPTION: main
12-12 10:28:41.300 18149 18149 E AndroidRuntime: Process: com.perflyst.twire, PID: 18149
12-12 10:28:41.300 18149 18149 E AndroidRuntime: java.lang.RuntimeException: Unable to invoke no-args constructor for com.google.common.base.Function<java.lang.String, java.lang.String>. Registering an InstanceCreator with Gson for this type may fix this problem.
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:228)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.google.gson.Gson.fromJson(Gson.java:932)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.google.gson.Gson.fromJson(Gson.java:897)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.google.gson.Gson.fromJson(Gson.java:846)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.perflyst.twire.service.Settings.getRecentEmotes(Settings.java:157)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.perflyst.twire.fragments.ChatFragment.loadRecentEmotes(ChatFragment.java:404)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.perflyst.twire.fragments.ChatFragment.onCreateView(ChatFragment.java:186)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:8018)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7664)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-12 10:28:41.300 18149 18149 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Interface can't be instantiated! Interface name: com.google.common.base.Function
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.google.gson.internal.UnsafeAllocator.assertInstantiable(UnsafeAllocator.java:117)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:49)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:225)
12-12 10:28:41.300 18149 18149 E AndroidRuntime:        ... 37 more`

**Comment by Hariiiiiiii** [comment] 2021-12-12 20:42
Temporary workaround is to disable the "connect to chat using your account" setting under twitch chat settings

**Comment by Nickwasused** [comment] 2021-12-13 12:56
Please tell us the following information:

1. Your Android Version
2. Your Twire Version
3. Are you using a custom Rom (yes/no)
4. Device Language
5. Changed Settings (e.g. Chat Settings)

**Comment by PLAYERUNKNOWNHatsune01** [comment] 2021-12-13 15:42
> Temporary workaround is to disable the "connect to chat using your account" setting under twitch chat settings

This fix the problem though

**Comment by Foexle11** [comment] 2021-12-28 18:43
Same Problem here
1. Android 11
2. 2.10.0 (FDroid)
3. No
4. German

Not shure if it helps in any way, but perhaps it helps finding the problem when its known on more than one device.
If you need a log or anything feel free to ask :D

**Comment by MarcoWilli** [comment] 2021-12-31 09:48
> Please tell us the following information:
> 
> 1. Your Android Version
> 2. Your Twire Version
> 3. Are you using a custom Rom (yes/no)
> 4. Device Language
> 5. Changed Settings (e.g. Chat Settings)

Same here for me. But must be very new as I usually use the app every day and did not only for a few days among Christmas. 

1. Android 10
2. 2.10.0
3. Yes. /e/ OS 0.19
4. German
5. Tried to update OS but did not went through
6.
Disabling chat works for me, too. 
Device is a Sony Xperia H3113

**Comment by Roph** [comment] 2022-01-01 14:35
Same problem here, instant crash immediately upon opening any stream on an Amazon Fire HD 8 2020 version.


Android Version: 9 (Latest Fire OS)
Twire Version: 2.10.0
Custom Rom: No (yes? FIre OS etc)
Language: English, UK
Settings stock except from logging in. 

Like others, disabling the "connect to chat using your account" option at least lets me watch.

**Comment by Nickwasused** [comment] 2022-01-01 15:18
@Foexle11 A log would be Great!

**Comment by Nickwasused** [comment] 2022-01-01 16:01
I can reproduce the Issue:
Log in
Join a Channel and send a Message with Emotes
Click Back
Close the App
Open the App
Try to watch a Stream
Crash

There is an issue with the Way we load the Recently used Emotes.

**Comment by Foexle11** [comment] 2022-01-01 16:09
> @Foexle11 A log would be Great!

Shure, no problem, if you would be so kind to tell me how ^^
Does Twire has a log function I'm just to blind to see or do I have to figure out how to use the ADB with my Linux PC?

**Comment by Nickwasused** [comment] 2022-01-01 18:53
Here is a test Apk built by Github Actions: [app.zip](https://github.com/twireapp/Twire/suites/4806514453/artifacts/135038296)
The Apk is based on #290 
(Github Run: https://github.com/twireapp/Twire/runs/4680615949?check_suite_focus=true)

**Comment by Roph** [comment] 2022-01-02 19:04
> 

Can confirm this fixes it

**Comment by Roph** [comment] 2022-01-02 19:05
> Here is a test Apk built by Github Actions: [app.zip](https://github.com/twireapp/Twire/suites/4806514453/artifacts/135038296)

I can confirm this fixes it

**Comment by Nickwasused** [comment] 2022-01-03 09:44
Here is another Apk for testing: [app.zip](https://github.com/twireapp/Twire/suites/4807789846/artifacts/135122920)
The Apk is based on #291 
(Github Run: https://github.com/twireapp/Twire/runs/4681986953)

**Comment by Foexle11** [comment] 2022-01-24 00:04
Sorry for the late response.
I cant download the last test-apk.
But, with the 2.10.1 it seems to work.
FDroid is kind of buggy here, so I cant be 100% shure if it updated or not.

**Comment by Nickwasused** [comment] 2022-02-04 06:27
Fixed in 2.10.1

**Closed by Nickwasused** 2022-02-04 06:27 UTC
Labels: bug, testing
