### ISSUE TITLE
Cant view rerun streamers

### ISSUE THREAD

**Issue by kaustos** [twireapp/Twire#287] opened 2021-12-26 16:22 UTC
Streamers who are "live" broadcasting reruns do not appear as online, and you can't join in viewing the stream that chat is, even if you manually choose the stream from Followed. Noted affected streamers are Kitboga and Katrine.

**Comment by Nickwasused** [comment] 2021-12-26 17:21
Duplicate of #171

**Closed by Nickwasused** 2021-12-26 17:21 UTC
