### ISSUE TITLE
Screen turns of on chat only mode.

### ISSUE THREAD

**Issue by Fatcakes** [twireapp/Twire#389] opened 2022-09-26 06:15 UTC
**Describe the bug**
Screen turns of on chat only mode.

**To Reproduce**
1. Go to a steam 
2. Click on 'gear'
3. Scroll down to chat only
4. Screen turns off depending on screen timeout time.

**Expected behavior**
Screen stays open to chat

**Smartphone (please complete the following information):**
 - Device:  Samsung a42
 - Android Version: Android 12]
 - Twire Version: 2.10.4

**Comment by samfundev** [comment] 2022-09-26 14:55
Duplicate of #380, should be available in the next release.

**Closed by samfundev** 2022-09-26 14:55 UTC
Labels: duplicate
