### ISSUE TITLE
Phone gets super warm to hot and drains battery?

### ISSUE THREAD

**Issue by Disnino** [twireapp/Twire#283] opened 2021-12-13 04:30 UTC
So yea pretty quick into watching on twire my phone just heats up and then requires me to stay connected to the charger or the battery will tank fast. I saw another one of these issue post things saying it has something to do with chat manager and ChatManager.doInBackground() causing super high cpu usage and that he was able to remove that lowering the cpu usage.

Can I do something to make twire run better or use less resources or do I just have to find some other twitch alternative. I have a Galaxy S9

**Comment by Disnino** [comment] 2021-12-13 08:16
Okay man this app is for sure mining bitcoin like wtf

**Comment by ein-bandit** [comment] 2021-12-13 11:53
it is an open source project. so you can check the codebase yourself if you have doubt. 
or invest in a capable phone

**Comment by Nickwasused** [comment] 2021-12-13 11:57
Duplicate of #197

**Closed by Nickwasused** 2021-12-13 11:57 UTC

**Comment by Disnino** [comment] 2021-12-13 11:58
> it is an open source project. so you can check the codebase yourself if you have doubt. or invest in a capable phone

So a Galaxy S9 isn't capable to run Twire? What would you call a capable phone to run an ad free twitch app cause I'm genuinely curious. I read the other issue question thing saying it is the process "chatmanager.doinbackground" or something like that and that causes the app to go to 180% xcpu usage and 77° and when he removed that the cpu usage went to 60% and 38°. Now I'm not exactly sure how that all works and I'm not saying thats specifically the issue here but I thought that was interesting.

Either way I installed the twitchmod apk and runs perfectly and my phone is icy cold so I'm wondering whats up with twire or like you say my phone just isn't capable to run such an app

**Comment by Disnino** [comment] 2021-12-13 12:08
> it is an open source project. so you can check the codebase yourself if you have doubt. or invest in a capable phone

So I found the twitchmod app and it runs like a charm and phone stays icy cold, so where's the leap to a Galaxy S9 isn't capable? I guess such a phone couldn't touch such a holy and complex app such as twire, you'd need the latest phone to run twitch right
