### ISSUE TITLE
Cannot maintain full screen mode when device is portrait locked

### ISSUE THREAD

**Issue by no-na** [twireapp/Twire#416] opened 2023-01-17 08:29 UTC
Encountered in Twire 2.10.5
Android 12, Galaxy S10

When my device's orientation setting is locked to 'portrait', pressing the full screen button on a stream causes the stream to briefly switch to landscape orientation before immediately reverting to portrait orientation.

In previous versions of Twire, expected behavior from pressing 'full screen' on a portrait locked device is that the video player switches to landscape orientation and maintains landscape orientation until the full screen button is pressed again, or until the device's back button is pressed.

**Comment by alvv-z** [comment] 2023-01-18 20:56
I am also having this issue on my Pixel 3 XL. Happens when pressing the button for full-screen and when turning the device and pressing on the round button in the corner to switch orientation.

**Comment by Soljanka** [comment] 2023-01-22 13:41
I can confirm this issue on both my Galaxy S8 (with Android 9) and A3 (Android 10). I did revert to version 2.10.4 to avoid the issue for now.

**Comment by ein-bandit** [comment] 2023-01-26 23:29
same issue.
seems to be related to accelerometer/gyro. when device moves the slightest bit physically the orientation changes

**Comment by alvv-z** [comment] 2023-01-28 11:02
A temporary fix for this is to disable the sensors permission for Twire, if you have a rom that can disable the sensors permission.

**Closed** 2023-04-30 02:44 UTC
Labels: bug
