### ISSUE TITLE
Keep Stream Running after locking

### ISSUE THREAD

**Issue by Cebrain** [twireapp/Twire#337] opened 2022-04-18 07:51 UTC
Hey,
i dont know if this is possible or an android limitation. Sometimes i would like to keep the stream running after locking the device, for example useful when the stream is running in audio mode.

**Comment by ScalableCodex** [comment] 2022-05-02 01:38
Would be great to have the ability to do this!

**Comment by samfundev** [comment] 2022-07-13 15:17
This is a duplicate of #99.

**Closed by samfundev** 2022-07-13 15:17 UTC
Labels: duplicate, enhancement
