### ISSUE TITLE
[Feature Request] Phone Notifications 

### ISSUE THREAD

**Issue by SneakyShrike** [twireapp/Twire#30] opened 2019-08-13 18:08 UTC
I think it would be cool to receive notifications when a streamer you follow goes live, like on the official Twitch app for android. Is this a possibility?

**Comment by Nickwasused** [comment] 2021-11-21 18:36
This is a duplicate of https://github.com/twireapp/Twire/issues/30

**Closed by Nickwasused** 2021-11-21 18:36 UTC
Labels: enhancement
