### ISSUE TITLE
Stream Timer starts but no video / no sound

### ISSUE THREAD

**Issue by 0tt3** [twireapp/Twire#423] opened 2023-04-23 18:45 UTC
Describe the bug
Everytime I open a stream, the preview picture and the play button show up. The play button turns into the pause button after a few seconds and the timer starts running but there is no video and no audio. Also, there are no video quality options to choose apart from "Auto". Chat works all right.

The whole thing started a few days ago. There was no update or anything.

Open a stream, see if it starts.

Expected behavior
Open a stream, video and audio start playing. Video quality can be chosen.

Smartphone (please complete the following information):

    Device: Motorola One Vision
    Android Version: 11
    Twire Version: 2.10.5

**Comment by longboarder241** [comment] 2023-04-24 04:33
I'm getting the same error 
Device: Palm Pepito PVG100
Android Version: 8.1
Twire Version: 2.10.5

**Comment by Whovian9369** [comment] 2023-04-24 06:22
I appear to be as well.

Device: Pixel 4a 5g
Android 13
Twire 2.10.5

**Comment by eebette** [comment] 2023-04-24 16:08
Same exact issue here on 2 devices.

Galaxy Tab S5e SM-T720
Android 11
Twire v2.10.5

Galaxy S22 SM-S901U1
Android 13
Twire v2.10.5

**Comment by LoneFenris** [comment] 2023-04-24 17:08
Likely the same issue as #422

**Comment by samfundev** [comment] 2023-04-30 03:01
I'm going to close this as a duplicate of #422. If this isn't fixed by 2.10.6, let me know!

**Closed by samfundev** 2023-04-30 03:01 UTC
Labels: duplicate
