### ISSUE TITLE
Background playing doesn't work

### ISSUE THREAD

**Issue by ugomeguerditchian** [twireapp/Twire#396] opened 2022-10-25 07:18 UTC
When you go to the player settings and activate the background playing it work juste few seconds after locking the screen, then, the audio stop

I'm on Samsung S10 android 12
Twice version 2.10.4

**Comment by KandiPanda** [comment] 2023-03-20 01:41
While not the same manufacturer or Android version as mine, you might check in **App info** > **Advanced** > **Battery** to see if **Battery optimization** is turned on for Twire, and if so disable it to see if that helps any.

**Comment by ugomeguerditchian** [comment] 2023-03-20 08:31
I've actually changed my phone.

I have a Pixel 7 pro with Android 13 and I still have the same issue even after deactivate the battery optimization for twire.

Picture in picture work but not the background playing.

**Comment by samfundev** [comment] 2023-04-03 18:45
Duplicate of #99

**Closed by samfundev** 2023-04-03 18:45 UTC
Labels: bug, needs exploration
