### ISSUE TITLE
Twire remember user even when logged out

### ISSUE THREAD

**Issue by Porkepix** [twireapp/Twire#7] opened 2019-04-04 22:24 UTC
I could notice it through `adb logcat` for another issue: after log in one time on Twire, and then log out, it seems to remember user information for the ChatManager component as I could still see my nickname in the logs.

**Comment by Nickwasused** [comment] 2021-12-13 16:44
I have tested this on 8555da1b25b6152f6208a34afb767f71df9846a1 and I am not able to reproduce the problem.

**Comment by samfundev** [comment] 2022-07-02 18:31
Closing since this appears to be fixed.

**Closed by samfundev** 2022-07-02 18:31 UTC
Labels: bug
