### ISSUE TITLE
I have to log in every time i use the app 

### ISSUE THREAD

**Issue by Ud4ba** [twireapp/Twire#185] opened 2021-01-23 11:37 UTC
That's idiotic . why I have to log in everyevery time I use the app ??? I set the remember me option .

**Comment by samfundev** [comment] 2021-01-23 16:15
I can't reproduce this problem, can you give me more information to help me reproduce the problem? Like are you using the latest version of Twire and what version of Android you using?

**Comment by Ud4ba** [comment] 2021-01-23 16:16
Sorry for my rage . Im using Android 10 with LinageOS 17.1 on a3lte . I have the latest version of twire . every time i have to log in in the app .

**Comment by samfundev** [comment] 2021-01-23 16:19
Sorry, I just realized that there is a similar issue opened. So I'm going to close this as a duplicate.

**Closed by samfundev** 2021-01-23 16:19 UTC
Labels: duplicate
