### ISSUE TITLE
7TV Not Working (2.11.0)

### ISSUE THREAD

**Issue by Dynamixus** [twireapp/Twire#456] opened 2024-12-27 13:09 UTC
**Describe the bug**
7TV emotes are not working, they just appear as text. I have them enabled.

**To Reproduce**
Enabled 7TV and disabled BTTV and FFZ emotes. The emote category of which I assume are from the extensions are just blank. When BTTV and FFZ is enabled there *are* emotes so gotta be a 7TV issue.

Tried restarting the app, my phone, deleting cache/reinstalling. 

**Expected behavior**
Should show the text as an emote.

**Smartphone (please complete the following information):**
 - Device: Realme C61
 - Android Version: Android 14
 - Twire Version: 2.11.0

**Comment by samfundev** [comment] 2024-12-29 01:34
Duplicate of #445

**Closed by samfundev** 2024-12-29 01:34 UTC
Labels: bug, needs exploration
