### ISSUE TITLE
Ability to keep the current stream keep playing when screen is locked

### ISSUE THREAD

**Issue by AssafHaft** [twireapp/Twire#448] opened 2024-08-02 01:44 UTC
I hate the new official App and found this perfect alternative!

My only issue is that I sometimes like to listen to streams while working out, is it possible to add a feature to continue listening to streams when the Phone screen is locked?

Thank you and amazing job!

**Comment by fidorulz** [comment] 2024-08-05 00:02
Totally agree. That's the only feature I miss since I found this great app.

Twitch has option for audio only mode same as this app but seems this app can't run in background when screen is off which I use often

**Comment by samfundev** [comment] 2024-08-08 01:13
Should be available in the next version.

Duplicate of #99

**Closed by samfundev** 2024-08-08 01:13 UTC
Labels: enhancement
