### ISSUE TITLE
Add clips tab and show all streamers clips

### ISSUE THREAD

**Issue by BeanBread98** [twireapp/Twire#306] opened 2022-01-31 08:18 UTC
When viewing a streamers profile, it only shows the description, broadcasts and highlights tabs on their channel page. Please add the clips tab and show all the clips of that particular streamer in the next update.

**Comment by Nickwasused** [comment] 2022-02-03 13:46
Duplicate of #130

**Closed by Nickwasused** 2022-02-03 13:46 UTC
Labels: duplicate
