### ISSUE TITLE
Stream delay

### ISSUE THREAD

**Issue by wannaskoo** [twireapp/Twire#199] opened 2021-02-27 22:47 UTC
I'm experiencing some stream delay, around 10 seconds. 
I checked against the default Twitch app and TwitchMod app (so i could check the latency with the advanced stats) and the delay is around 1-2 seconds. I'm also ruling out my internet speed since i have a Gigabit fiber. 

Edit: Looking into the TwitchMod Telegram channel someone asked how to disable Low Latency mode and the answer was to switch player from PlayerCore to Exoplayer. That tells me that Exoplayer (and also Twire) lack Low Latency mode support, did i understand this correctly?

**Comment by samfundev** [comment] 2021-03-13 18:06
From what I can tell "PlayerCore" is a proprietary piece of software used by Twitch that I can't add to Twire. TwitchMod is able to use it because they are just modifying the Twitch app which has PlayerCore in it. Fortunately, ExoPlayer has made some developments on adding support for low latency. I need to look into if they added support for the low latency streaming method that Twitch uses. I am going to close this issue as it's a duplicate of #94.

**Closed by samfundev** 2021-03-13 18:06 UTC
Labels: duplicate

**Comment by wannaskoo** [comment] 2021-03-13 18:38
1) I know that Playercore is proprietary, i just wanted to understand the reason of the delay.
2) I'm sorry for wasting your time by opening another issue. I checked for similar issues before posting, but i may have missed that. 
Also i'm rooting for this project a lot and always testing new releases. Thanks for your fime and effort.
