### ISSUE TITLE
Notification When Streamer Goes Live

### ISSUE THREAD

**Issue by uuuussseer** [twireapp/Twire#260] opened 2021-11-12 12:36 UTC
This has been mentioned in two previous issues, #14 and #30, but no action has actually been made on this feature which I feel is really important.

Notifications are important, since most people aren't checking the app every ten or so minutes to see when someone is live, they may miss the stream. While there are email notifications for people who have a account, for users who are don't have a account and are following people, (if pull request #240 gets accepted) it would be pretty much the _only_ way to get notifications for when streamers go live.

In the conversation from issue #14, (posted in the comment below) having a timer to check the followed streamers is mentioned. If this is a valid idea that could realistically be implemented, I think it would be a great solution to this problem.

Hopefully this issue can create some well needed discourse since the developers seem to be active again. Thanks!

**Comment by uuuussseer** [comment] 2021-11-12 21:33
I'll also post the conversation that happened on #14 because I think it's relevant and poses some good ideas that can be built upon.

Person One:
> Send a feed when one of streamers is on live

Person Two:
> Do you mean a push notification that lets you know that a streamer, that you follow and want notifications of, went live?

Person One:
> Yes

Person Three:
> You need some kind of persistent connection for that, right ?
Or maybe a sort of timer, checking every X minutes all of your follow.
First solution seems difficult without GCM

Person Four:
>bump
I think checking every 5-15 minutes is fine.

**Comment by Nickwasused** [comment] 2021-11-21 18:35
This is a duplicate of https://github.com/twireapp/Twire/issues/30

**Closed by Nickwasused** 2021-11-21 18:35 UTC
Labels: duplicate, enhancement
