### ISSUE TITLE
App crashes on stream playback - Android 7.1.2

### ISSUE THREAD

**Issue by Staycalmsyndrome** [twireapp/Twire#370] opened 2022-07-21 19:56 UTC
It crashes when i try to play any stream. This does not happen on 2.10.2.

 - Device: Galaxy Tab S2
 - Android Version: 7.1.2
 - Twire Version: 2.10.3

**Comment by samfundev** [comment] 2022-07-21 20:04
Duplicate of #361, should be a new release soon.

**Closed by samfundev** 2022-07-21 20:04 UTC
Labels: bug, duplicate

**Comment by Staycalmsyndrome** [comment] 2022-07-21 20:11
thank you.
