### ISSUE TITLE
Support for background playback?

### ISSUE THREAD

**Issue by framilano** [twireapp/Twire#296] opened 2022-01-12 13:07 UTC
Is there any chance to have this feature anytime soon?
With background playback I mean audio-only playback when the screen is off.

**Comment by samfundev** [comment] 2022-02-16 17:40
Duplicate of #99

**Closed by samfundev** 2022-02-16 17:40 UTC
Labels: duplicate, enhancement

**Comment by nbros** [comment] 2022-05-15 10:19
As a workaround I noticed that that you can click "Use external player" from the upper right hamburger menu in Twire in order to start playing in VLC for example which does support background playback!
