### ISSUE TITLE
"commercial break in progress" for every stream

### ISSUE THREAD

**Issue by digital-mystik** [twireapp/Twire#134] opened 2020-09-18 05:08 UTC
Haven't been on in a little while but I'm guessing Twitch has changed their API or something along those lines. Looks like ads are blocked but the placeholder is there.

**Comment by Kusurisan** [comment] 2020-09-20 20:21
now streams don't work at all anymore. same goes for pocket plays from the playstore.. sad.

**Comment by ikrevem** [comment] 2020-09-21 11:15
Hi, actually for me streams are working fine both in Twire and in Pocket Plays from Play Store.

Regarding the "Commercial break in progress" issue, it has been solved in 1d94979, but the updated version of Twire, which include this commit, has not been released yet. Anyway, since the "Commercial break in progress" screen was bothering me, I've decided to compile Twire by myself and I can confirm that the ads are completely blocked! So, you can directly compile it or wait for the official release.

**Comment by vlamacko** [comment] 2020-09-21 15:01
Duplicate of #85

**Closed** 2020-09-21 15:16 UTC

**Comment by samfundev** [comment] 2020-09-22 02:45
Really sorry I haven't gotten the update out, I'm going to try to get it out soon.
