### ISSUE TITLE
Make Twire UI useable for Nvidia Shield TV

### ISSUE THREAD

**Issue by GitJamz** [twireapp/Twire#163] opened 2020-11-21 21:20 UTC
Hi,

Love Twire for my phone but recently I got a nvidia shield TV that I use for my TV.

I tried the Twire app there and the UI is not great of course but I can live with that.
The problem is that you need a mouse to navigate through the UI. 

If someone could program the UI navigation from a controller of some kind that would be awesome! There is not much missing I would say but for example moving around with the <- -> arrows shows no highlights of where you are etc..

Please make this work! Would really love it.. If a developer wanna do this on a evening PM me and I can donate a pizza and a beer for your efforts.

Peace

**Comment by samfundev** [comment] 2020-11-25 05:36
Thanks for the request. I'm going to close this as a duplicate of #121.

**Closed by samfundev** 2020-11-25 05:36 UTC
Labels: duplicate
