### ISSUE TITLE
2.10.2 broke streams

### ISSUE THREAD

**Issue by gerroon** [twireapp/Twire#325] opened 2022-02-27 00:48 UTC
Hi

I upgraded  to 2.10.2 using Fdroid now I see no streams or anything, every tab is basically empty. I did not have such an issue with the previous version. 

All tabs like Top streams, Featured streams etc are literally empty, nothing is listed in those windows.

I am using LineageOS 18.1 

thanks

**Comment by AitoZ** [comment] 2022-02-27 08:16
You have to login, you can't use the new Twitch API without an account. Before you open a new issue, there's a few bugs in the latest version that should be fixed in the next update.

**Comment by Nickwasused** [comment] 2022-02-27 15:10
Duplicate of #314

**Closed by Nickwasused** 2022-02-27 15:10 UTC
Labels: duplicate, Account / Helix / Kraken
